chronicleworks/chronicle-examples

- README.md
Signed-off-by: Kevin O'Donnell <kevin@blockchaintp.com>
> docs: update README.md to reference docs and prereqs

- Makefile
- docker/chronicle.dockerfile
- docker/docker-compose.yaml
Signed-off-by: Kevin O'Donnell <kevin@blockchaintp.com>
> fix(docker): allow easy override of chronicle-builder image

- README.md
- domains/manufacturing/guide.md
Signed-off-by: Duncan Johnston-Watt <duncan@blockchaintp.com>
> docs: update manu guide and README

- domains/manufacturing/guide.md
- quick set of copy edits upon reading through
---
Signed-off-by: Joseph Livesey <joseph@blockchaintp.com>
> docs: copy edit guides

- domains/artworld/domain.yaml
- domains/evidence/domain.yaml
Role names may not contain lowercase characters.
> update artworld and evidence domains for Chronicle v0.3.0

- Makefile
prevent surprises
Signed-off-by: Kevin O'Donnell <kevin@blockchaintp.com>
> build(deps): pin chronicle-builder version to BTP2.1.0-0.3.0

- Makefile
- docker/chronicle.dockerfile
- domains/evidence/domain.yaml
- domains/manufacturing/domain.yaml
- domains/manufacturing/guide.md
* Fix the lower case role errors it found
Dependent on a .4 release of Chronicle
Signed-off-by: Ryan Roberts <ryan@blockchaintp.com>
> feat: Run linter before compilation

- README.md
See [CHRON-150](https://blockchaintp.atlassian.net/browse/CHRON-150).
> have README encourage an accompanying, conforming guide.md

- domains/manufacturing/guide.md
GraphQL responses are JSON data.
> Highlight GraphQL responses as JSON in the guide

- domains/corporate-actions/guide.md
A collaborative effort by myself and @csillazs to add mutation and query examples.
Signed-off-by: Joseph Livesey <joseph.livesey@btp.works>
> Expand corporate actions guide

- domains/corporate-actions/guide.md
> docs: upd corp-actions guide

- domains/corporate-actions/guide.md
> docs: fix nominal price after share split

- domains/corporate-actions/guide.md
> docs: batch mutations

- .pre-commit-config.yaml
> fix: drop pre-commit-java

- README.md
> docs: add corp actions to README

- docs/diagrams/include/time-recording_Approve.iuml
- docs/diagrams/include/time-recording_Person.iuml
- docs/diagrams/include/time-recording_Person1.iuml
- docs/diagrams/include/time-recording_Person2.iuml
- docs/diagrams/include/time-recording_Person3.iuml
- docs/diagrams/include/time-recording_Project.iuml
- docs/diagrams/include/time-recording_Reject.iuml
- docs/diagrams/include/time-recording_Revision.iuml
- docs/diagrams/include/time-recording_Submit.iuml
- docs/diagrams/include/time-recording_Summary.iuml
- docs/diagrams/include/time-recording_Timesheet.iuml
- docs/diagrams/include/time-recording_View.iuml
- docs/diagrams/include/time-recording_Work.iuml
- docs/diagrams/include/time-recording_Work1.iuml
- docs/diagrams/include/time-recording_Work2.iuml
- docs/diagrams/src/time-recording_DelegationExample.puml
- docs/diagrams/src/time-recording_ProjectSummary.puml
- docs/diagrams/src/time-recording_RecordTime.puml
- docs/diagrams/src/time-recording_ReportTime.puml
- docs/diagrams/src/time-recording_ReviseOnBehalf.puml
- docs/diagrams/src/time-recording_SubmitOnBehalf.puml
- docs/diagrams/src/time-recording_SubmitTimesheet.puml
- docs/diagrams/src/time-recording_ViewTimesheet.puml
[CHRON-193](https://blockchaintp.atlassian.net/browse/CHRON-193)
> have time recording domain diagrams match chosen style

- docs/diagrams/src/manufacturing_ItemCertified.puml
- docs/diagrams/src/manufacturing_ItemManufactured.puml
Signed-off-by: Joseph Livesey [joseph.livesey@btp.works](mailto:joseph.livesey@btp.works)
> fix: edit manufacturing diagrams for greater clarity

- docs/diagrams/include/manufacturing_certificate.iuml
- docs/diagrams/include/manufacturing_contractor.iuml
- docs/diagrams/include/manufacturing_item.iuml
- docs/diagrams/include/manufacturing_item_manufactured.iuml
Signed-off-by: Duncan Johnston-Watt <duncan@blockchaintp.com>
> docs: update manufacturing attributes

- docs/diagrams/include/activity.iuml
- docs/diagrams/include/agent.iuml
- docs/diagrams/include/entity.iuml
- docs/diagrams/src/corporate-actions_ShareholdingAcquired.puml
- docs/diagrams/src/corporate-actions_ShareholdingUpdated.puml
- docs/diagrams/src/corporate-actions_SplitAnnounced.puml
- docs/diagrams/src/manufacturing_ItemCertified.puml
- docs/diagrams/src/manufacturing_ItemManufactured.puml
- docs/diagrams/src/time-recording_ProjectSummary.puml
- docs/diagrams/src/time-recording_RecordTime.puml
- docs/diagrams/src/time-recording_ReportTime.puml
- docs/diagrams/src/time-recording_ReviseOnBehalf.puml
- docs/diagrams/src/time-recording_SubmitTimesheet.puml
- docs/diagrams/src/time-recording_ViewTimesheet.puml
[CHRON-216](https://blockchaintp.atlassian.net/browse/CHRON-216?atlOrigin=eyJpIjoiODJlM2UxMWJmN2VkNDQzZDliMWI1Y2IzNDY3NDk3YWYiLCJwIjoiaiJ9)
Signed-off-by: Joseph Livesey <joseph.livesey@btp.works>
[CHRON-216]: https://blockchaintp.atlassian.net/browse/CHRON-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: edit diagrams according to spec

- domains/artworld/guide.md
[CHRON-235](https://blockchaintp.atlassian.net/browse/CHRON-235)
Signed-off-by: Joseph Livesey <joseph.livesey@btp.works>
[CHRON-235]: https://blockchaintp.atlassian.net/browse/CHRON-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(artworld): write guide

- README.md
Signed-off-by: Kevin O'Donnell <kevin@blockchaintp.com>
> docs: add link to examples doc site

- Makefile
Fixes CHRON-247 by allowing the linter output to reach the user's console.
> run domain linter before building an image

- domains/artworld/domain.yaml
- domains/corporate-actions/domain.yaml
- domains/manufacturing/domain.yaml
- domains/scienceproject/domain.yaml
Signed-off-by: Joseph Livesey [joseph.livesey@btp.works](mailto:joseph.livesey@btp.works)
> fix(domains): remove quotes around type arguments in domain.yaml

- Makefile
- docker/chronicle-domain.yaml
* There are intermittent errors with pg_embed
* Use compose with a pg instance rather than run
References: CHRON-264
> fix: Use a real pg instance

- Jenkinsfile
- Makefile
- docker/chronicle-test/chronicle-test
- docker/chronicle-test/chronicle-test.dockerfile
- docker/chronicle-test/wait-for-it
- docker/chronicle.yaml
* Lint all domains
* Run e2e test for artworld
This should cover both domain contributions and upstream updates to Chronicle in CI
> fix: Make CI process appropriate

- domains/time-recording/guide.md
Followup to https://github.com/btpworks/chronicle/pull/254 fixing the order of delegation participants.
> update delegation query results for time recording

- Makefile
- README.md
- docker/chronicle-test.yaml
> do not use docker compose profiles

- README.md
Resolves CHRON-369 as best as presently achievable given urgency.
> expand description of makefile targets

- README.md
> adjust description of makefile targets

- docker/chronicle-domain.yaml
Companion to https://github.com/btpworks/chronicle-bootstrap/pull/10.
> Don't provide --unlock-cors option.

- Makefile
- docker/chronicle-domain.yaml
- docker/chronicle.yaml
> feat(makefile): pass variables from file into chronicle environment

- README.md
> fix(readme): fix broken links to examples

- README.md
> document the docker/chronicle-environment file

- docker/chronicle-test/chronicle-test.dockerfile
- domains/artworld/COPYRIGHT
- domains/corporate-actions/COPYRIGHT
- domains/manufacturing/COPYRIGHT
- domains/scienceproject/COPYRIGHT
- domains/time-recording/COPYRIGHT
> docs: update ownership following IP assignation

- README.md
> docs: fix readme ref

- Makefile
- docker/chronicle-domain.yaml
- docker/chronicle.dockerfile
* Image versions
* Example execution unbuntu updated to jammy, as new binaries need a more modern libc
* Default log level lowered from trace, as it's a little hard on some terminals
> * Update to 0.7.6

- Makefile
> Update to 0.7.7

- domains/manufacturing/guide.md
> docs: clarify bidirectional relationship generated is inferred not asserted
